[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/citizen"
  to = "/citizen.html"
  status = 200

[[redirects]]
  from = "/sms"
  to = "/vonage-sms.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
